version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Pre-build phase"
      - java -version
      - mvn -version
  build:
    commands:
      - echo "Build phase"
      - mvn clean package
  post_build:
    commands:
      - echo "Post-build phase"
artifacts:
  files:
    - target/*.jar
    - src/main/resources/static/**/*
  discard-paths: no
