
gitignore: true
aws:
  access-key-id: AKIAZOZQFZUTHQ5LFQYR
  secret-access-key: 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
  region: ${AWS_REGION:us-east-2}

server:
  port: 8080
spring:
  application:
    name: career-adventure
