
gitignore: true
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION:us-east-2}

server:
  port: 8080
spring:
  application:
    name: career-adventure
